apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
  labels:
    app: app4
  namespace: namespace-workflow-1684874648606
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
        - name: app4
          image: akstestcr011.azurecr.io/image-workflow-1684874648606:latest
          ports:
            - containerPort: 8000