apiVersion: apps/v1
kind: Deployment
metadata:
  name: app5
  labels:
    app: app5
  namespace: namespace-workflow-1684875970296
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app5
  template:
    metadata:
      labels:
        app: app5
    spec:
      containers:
        - name: app5
          image: akstestcr011.azurecr.io/image-workflow-1684875970296:latest
          ports:
            - containerPort: 8000