apiVersion: v1
kind: Service
metadata:
  name: app4
  namespace: namespace-workflow-1684874648606
spec:
  type: LoadBalancer
  selector:
    app: app4
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000