apiVersion: v1
kind: Service
metadata:
  name: app5
  namespace: namespace-workflow-1684875970296
spec:
  type: LoadBalancer
  selector:
    app: app5
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000